export const newsData = [
  {
    headline:
      "Headline: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum, nunc ut sollicitudin",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
  },
  {
    headline:
      "Headline: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum, nunc ut sollicitudin",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
  },
  {
    headline:
      "Headline: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum, nunc ut sollicitudin",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
  },
  {
    headline:
      "Headline: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum, nunc ut sollicitudin",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
  },
  {
    headline:
      "Headline: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum, nunc ut sollicitudin",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
  },
];

export const CountryTrendsData = [
  {
    Date: "2017",
    Planned: 100,
    Construction: 100,
    Retired: 0,
    Halted: 222,
    Cancelled: 100,
    Operational: 550,
  },
  {
    Date: "2018",
    Planned: 100,
    Construction: 90,
    Retired: -10,
    Halted: 202,
    Cancelled: 100,
    Operational: 570,
  },
  {
    Date: "2019",
    Planned: 100,
    Construction: 100,
    Retired: -4,
    Halted: 132,
    Cancelled: 100,
    Operational: 570,
  },
  {
    Date: "2020",
    Planned: 100,
    Construction: 90,
    Retired: -50,
    Halted: 102,
    Cancelled: 100,
    Operational: 590,
  },
  {
    Date: "2021",
    Planned: 100,
    Construction: 85,
    Retired: -112,
    Halted: 82,
    Cancelled: 100,
    Operational: 610,
    Expected: -100,
  },
];

export const TotalCapacityData = [
  {
    color: "hsl(15, 70%, 50%)",
    data: [
      {
        x: "2000",
        y: 1043062,
      },
      {
        x: "2005",
        y: 3043062,
      },
      {
        x: "2010",
        y: 10043062,
      },
      {
        x: "2015",
        y: 18043062,
      },
      {
        x: "2020",
        y: 21043062,
      },
    ],
  },
];

export const CurrentCapacityStatusData = [
  {
    id: "OPERATIONAL",
    label: " OPERATIONAL",
    value: 206,
  },
  {
    id: "CONSTRUCTION",
    label: "CONSTRUCTION",
    value: 379,
  },
  {
    id: "PLANNED",
    label: "PLANNED",
    value: 223,
  },
  {
    id: "HALTED",
    label: "HALTED",
    value: 412,
  },
  {
    id: "CANCELLED",
    label: "CANCELLED",
    value: 200,
  },
  {
    id: "RETIRED",
    label: "RETIRED",
    value: 278,
  },
];

export const CurrentCapacityTechnologyData = [
  {
    id: "SUBCRITICAL",
    label: " SUBCRITICAL",
    value: 400,
  },
  {
    id: "SUPERCRITICAL",
    label: "SUPERCRITICAL",
    value: 200,
  },
  {
    id: "ULTRA_SUPERCRITICAL",
    label: "ULTRA_SUPERCRITICAL",
    value: 100,
  },
  {
    id: "OTHER",
    label: "OTHER",
    value: 300,
  },
  {
    id: "UNKNOWN",
    label: "UNKNOWN",
    value: 400,
  },
];

export const countryData = [
  {
    Date: "2010",
    Planned: 100,
    Construction: 100,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
  },
  {
    Date: "2011",
    Planned: 100,
    Construction: 90,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
  },
  {
    Date: "2012",
    Planned: 100,
    Construction: 100,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
  },
  {
    Date: "2013",
    Planned: 100,
    Construction: 300,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
  },
  {
    Date: "2014",
    Planned: 100,
    Construction: 40,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
  },
  {
    Date: "2015",
    Planned: 100,
    Construction: 293,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
  },
  {
    Date: "2016",
    Planned: 100,
    Construction: 293,
    Retired: -32,
    Halted: 424,
    Cancelled: 111,
    Operational: 600,
    Expected: -444,
  },
  {
    Date: "2017",
    Planned: 100,
    Construction: 293,
    Retired: -323,
    Halted: 32,
    Cancelled: 111,
    Operational: 600,
    Expected: -200,
  },
  {
    Date: "2018",
    Planned: 100,
    Construction: 293,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
    Expected: -200,
  },
  {
    Date: "2019",
    Planned: 100,
    Construction: 293,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
    Expected: -200,
  },
  {
    Date: "2020",
    Planned: 100,
    Construction: 293,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
    Expected: -200,
  },
  {
    Date: "2021",
    Planned: 100,
    Construction: 293,
    Retired: -172,
    Halted: 222,
    Cancelled: 100,
    Operational: 600,
    Expected: -200,
  },
];

export const ageData = [
  {
    id: "0.0",
    group: "group A",
    price: 130,
    volume: 17,
  },
  {
    id: "0.1",
    group: "group A",
    price: 127,
    volume: 11,
  },
  {
    id: "0.2",
    group: "group A",
    price: 77,
    volume: 14,
  },
  {
    id: "0.3",
    group: "group A",
    price: 110,
    volume: 11,
  },
  {
    id: "0.4",
    group: "group A",
    price: 337,
    volume: 15,
  },
  {
    id: "0.5",
    group: "group A",
    price: 166,
    volume: 6,
  },
  {
    id: "0.6",
    group: "group A",
    price: 340,
    volume: 6,
  },
  {
    id: "0.7",
    group: "group A",
    price: 167,
    volume: 7,
  },
  {
    id: "0.8",
    group: "group A",
    price: 241,
    volume: 13,
  },
  {
    id: "0.9",
    group: "group A",
    price: 271,
    volume: 13,
  },
  {
    id: "0.10",
    group: "group A",
    price: 8,
    volume: 19,
  },
  {
    id: "0.11",
    group: "group A",
    price: 183,
    volume: 17,
  },
  {
    id: "0.12",
    group: "group A",
    price: 129,
    volume: 15,
  },
  {
    id: "0.13",
    group: "group A",
    price: 384,
    volume: 5,
  },
  {
    id: "0.14",
    group: "group A",
    price: 171,
    volume: 6,
  },
  {
    id: "0.15",
    group: "group A",
    price: 170,
    volume: 15,
  },
  {
    id: "0.16",
    group: "group A",
    price: 356,
    volume: 17,
  },
  {
    id: "0.17",
    group: "group A",
    price: 448,
    volume: 19,
  },
  {
    id: "0.18",
    group: "group A",
    price: 308,
    volume: 15,
  },
  {
    id: "0.19",
    group: "group A",
    price: 227,
    volume: 17,
  },
  {
    id: "0.20",
    group: "group A",
    price: 238,
    volume: 12,
  },
  {
    id: "0.21",
    group: "group A",
    price: 410,
    volume: 8,
  },
  {
    id: "0.22",
    group: "group A",
    price: 28,
    volume: 11,
  },
  {
    id: "0.23",
    group: "group A",
    price: 395,
    volume: 10,
  },
  {
    id: "0.24",
    group: "group A",
    price: 0,
    volume: 7,
  },
  {
    id: "0.25",
    group: "group A",
    price: 414,
    volume: 13,
  },
  {
    id: "0.26",
    group: "group A",
    price: 380,
    volume: 10,
  },
  {
    id: "0.27",
    group: "group A",
    price: 329,
    volume: 20,
  },
  {
    id: "0.28",
    group: "group A",
    price: 399,
    volume: 13,
  },
  {
    id: "0.29",
    group: "group A",
    price: 482,
    volume: 17,
  },
  {
    id: "0.30",
    group: "group A",
    price: 264,
    volume: 18,
  },
  {
    id: "0.31",
    group: "group A",
    price: 456,
    volume: 11,
  },
  {
    id: "0.32",
    group: "group A",
    price: 446,
    volume: 16,
  },
  {
    id: "0.33",
    group: "group A",
    price: 331,
    volume: 19,
  },
  {
    id: "0.34",
    group: "group A",
    price: 134,
    volume: 12,
  },
  {
    id: "0.35",
    group: "group A",
    price: 276,
    volume: 17,
  },
  {
    id: "0.36",
    group: "group A",
    price: 433,
    volume: 13,
  },
  {
    id: "0.37",
    group: "group A",
    price: 419,
    volume: 8,
  },
  {
    id: "0.38",
    group: "group A",
    price: 244,
    volume: 8,
  },
  {
    id: "0.39",
    group: "group A",
    price: 377,
    volume: 14,
  },
  {
    id: "0.40",
    group: "group A",
    price: 291,
    volume: 8,
  },
  {
    id: "0.41",
    group: "group A",
    price: 111,
    volume: 9,
  },
  {
    id: "0.42",
    group: "group A",
    price: 348,
    volume: 20,
  },
  {
    id: "0.43",
    group: "group A",
    price: 405,
    volume: 19,
  },
  {
    id: "0.44",
    group: "group A",
    price: 143,
    volume: 6,
  },
  {
    id: "0.45",
    group: "group A",
    price: 157,
    volume: 7,
  },
  {
    id: "0.46",
    group: "group A",
    price: 307,
    volume: 16,
  },
  {
    id: "0.47",
    group: "group A",
    price: 1,
    volume: 20,
  },
  {
    id: "0.48",
    group: "group A",
    price: 411,
    volume: 15,
  },
  {
    id: "0.49",
    group: "group A",
    price: 111,
    volume: 8,
  },
  {
    id: "0.50",
    group: "group A",
    price: 336,
    volume: 11,
  },
  {
    id: "0.51",
    group: "group A",
    price: 65,
    volume: 12,
  },
  {
    id: "0.52",
    group: "group A",
    price: 433,
    volume: 18,
  },
  {
    id: "0.53",
    group: "group A",
    price: 370,
    volume: 16,
  },
  {
    id: "0.54",
    group: "group A",
    price: 4,
    volume: 4,
  },
  {
    id: "0.55",
    group: "group A",
    price: 412,
    volume: 16,
  },
  {
    id: "0.56",
    group: "group A",
    price: 441,
    volume: 4,
  },
  {
    id: "0.57",
    group: "group A",
    price: 353,
    volume: 5,
  },
  {
    id: "0.58",
    group: "group A",
    price: 187,
    volume: 4,
  },
  {
    id: "0.59",
    group: "group A",
    price: 429,
    volume: 18,
  },
  {
    id: "0.60",
    group: "group A",
    price: 95,
    volume: 10,
  },
  {
    id: "0.61",
    group: "group A",
    price: 401,
    volume: 6,
  },
  {
    id: "0.62",
    group: "group A",
    price: 189,
    volume: 9,
  },
  {
    id: "0.63",
    group: "group A",
    price: 189,
    volume: 19,
  },
  {
    id: "0.64",
    group: "group A",
    price: 294,
    volume: 20,
  },
  {
    id: "0.65",
    group: "group A",
    price: 406,
    volume: 4,
  },
  {
    id: "0.66",
    group: "group A",
    price: 157,
    volume: 16,
  },
  {
    id: "0.67",
    group: "group A",
    price: 338,
    volume: 18,
  },
  {
    id: "0.68",
    group: "group A",
    price: 302,
    volume: 13,
  },
  {
    id: "0.69",
    group: "group A",
    price: 221,
    volume: 9,
  },
  {
    id: "0.70",
    group: "group A",
    price: 267,
    volume: 18,
  },
];

export const GlobalCoalPlantsStatusData = [
  {
    status: "Operating",
    color: "#DF0000",
    value: 2_059,
  },
  {
    status: "Construction",
    color: "#E27426",
    value: 180,
  },
  {
    status: "Planned",
    color: "#F4BE44",
    value: 89,
  },
  {
    status: "Halted",
    color: "#4F338A",
    value: 152,
  },
  {
    status: "Retired",
    color: "#4D9C98",
    value: 1_646,
  },
];

export const coal_plants_by_status: { [key: string]: number } = {
  operational: 2083,
  construction: 190,
  planned: 347,
  halted: 115,
  cancelled: 1752,
  retired: 474,
};

export interface IEmissionPathway {
  current: number;
  no_action: number;
  target_1_5_deg: number;
  target_2_deg: number;
  year: number;
}
export const EmissionPathways: IEmissionPathway[] = [
  {
    year: 2010,
    current: 8.9,
    no_action: 8.9,
    target_1_5_deg: 8.9,
    target_2_deg: 8.9,
  },
  {
    year: 2015,
    current: 9.6,
    no_action: 9.6,
    target_1_5_deg: 9.6,
    target_2_deg: 9.6,
  },
  {
    year: 2020,
    current: 9.5,
    no_action: 11.2,
    target_1_5_deg: 9.5,
    target_2_deg: 9.5,
  },
  {
    year: 2025,
    current: 10,
    no_action: 12.1,
    target_1_5_deg: 6.2,
    target_2_deg: 9.1,
  },
  {
    year: 2030,
    current: 10,
    no_action: 13.2,
    target_1_5_deg: 3,
    target_2_deg: 7.8,
  },
  {
    year: 2035,
    current: 10.1,
    no_action: 14.1,
    target_1_5_deg: 1,
    target_2_deg: 6.2,
  },
  {
    year: 2040,
    current: 10.1,
    no_action: 14.9,
    target_1_5_deg: 0.3,
    target_2_deg: 4,
  },
  {
    year: 2045,
    current: 10.1,
    no_action: 15.6,
    target_1_5_deg: 0.1,
    target_2_deg: 1.7,
  },
  {
    year: 2050,
    current: 10.2,
    no_action: 16.4,
    target_1_5_deg: 0,
    target_2_deg: 0.6,
  },
];

export const country_rankings_by_status = {
  operational: [
    {
      country: "China",
      capacity_mw: 1042944,
    },
    {
      country: "United States",
      capacity_mw: 233625,
    },
    {
      country: "India",
      capacity_mw: 229254,
    },
    {
      country: "Japan",
      capacity_mw: 47872,
    },
    {
      country: "Russia",
      capacity_mw: 44845,
    },
    {
      country: "Germany",
      capacity_mw: 42527,
    },
    {
      country: "South Africa",
      capacity_mw: 41905,
    },
    {
      country: "South Korea",
      capacity_mw: 36380,
    },
    {
      country: "Indonesia",
      capacity_mw: 33966,
    },
    {
      country: "Poland",
      capacity_mw: 30201,
    },
  ],
  construction: [
    {
      country: "China",
      capacity_mw: 88130,
    },
    {
      country: "India",
      capacity_mw: 36635,
    },
    {
      country: "Indonesia",
      capacity_mw: 10739,
    },
    {
      country: "Japan",
      capacity_mw: 7318,
    },
    {
      country: "South Korea",
      capacity_mw: 7260,
    },
    {
      country: "Vietnam",
      capacity_mw: 6820,
    },
    {
      country: "Bangladesh",
      capacity_mw: 4754,
    },
    {
      country: "South Africa",
      capacity_mw: 3975,
    },
    {
      country: "Pakistan",
      capacity_mw: 3300,
    },
    {
      country: "United Arab Emirates",
      capacity_mw: 2400,
    },
  ],
  planned: [
    {
      country: "China",
      capacity_mw: 158734,
    },
    {
      country: "India",
      capacity_mw: 29289,
    },
    {
      country: "Indonesia",
      capacity_mw: 22210,
    },
    {
      country: "Vietnam",
      capacity_mw: 21880,
    },
    {
      country: "Turkey",
      capacity_mw: 18731,
    },
    {
      country: "Bangladesh",
      capacity_mw: 16950,
    },
    {
      country: "Philippines",
      capacity_mw: 6720,
    },
    {
      country: "Mongolia",
      capacity_mw: 6630,
    },
    {
      country: "Zimbabwe",
      capacity_mw: 4190,
    },
    {
      country: "Pakistan",
      capacity_mw: 4148,
    },
  ],
  halted: [
    {
      country: "China",
      capacity_mw: 648497,
    },
    {
      country: "India",
      capacity_mw: 601567,
    },
    {
      country: "Turkey",
      capacity_mw: 79277,
    },
    {
      country: "Vietnam",
      capacity_mw: 48465,
    },
    {
      country: "Indonesia",
      capacity_mw: 35820,
    },
    {
      country: "United States",
      capacity_mw: 28168,
    },
    {
      country: "Pakistan",
      capacity_mw: 24030,
    },
    {
      country: "Poland",
      capacity_mw: 22383,
    },
    {
      country: "Myanmar",
      capacity_mw: 21225,
    },
    {
      country: "Germany",
      capacity_mw: 20413,
    },
  ],
  retired: [
    {
      country: "United States",
      capacity_mw: 127195,
    },
    {
      country: "China",
      capacity_mw: 112966,
    },
    {
      country: "United Kingdom",
      capacity_mw: 29728,
    },
    {
      country: "Germany",
      capacity_mw: 23497,
    },
    {
      country: "India",
      capacity_mw: 13310,
    },
    {
      country: "Canada",
      capacity_mw: 10892,
    },
    {
      country: "Spain",
      capacity_mw: 8964,
    },
    {
      country: "Australia",
      capacity_mw: 7007,
    },
    {
      country: "France",
      capacity_mw: 6122,
    },
    {
      country: "Poland",
      capacity_mw: 5909,
    },
  ],
};

export const powerEnergy = [
  {
    Name: "INDONESIA",
    bioenergy: 0,
    coal: 0,
    gas: 126,
    hydro: 0,
    nuclear: 0,
    other_fossil: 0,
    other_renewables: 0,
    wind: 0,
    solar: 4,
  },
  {
    Name: "WORLD",
    bioenergy: 586,
    coal: 8736,
    gas: 5892,
    hydro: 4355,
    nuclear: 2617,
    other_fossil: 1128,
    other_renewables: 117,
    wind: 1590,
    solar: 844,
  },
];

export const countryEnergy = [
  {
    Name: "Country Energy Mix",
    Nuclear: 100,
    Solar: 293,
    Bioenergy: 100,
    Hydro: 172,
    Gas: 222,
    Coal: 100,
    Renewables: 100,
    Wind: 70,
    Other: 200,
  },
];

export const worldEnergy = [
  {
    Name: "World Energy Mix",
    Nuclear: 100,
    Solar: 293,
    Bioenergy: 100,
    Hydro: 172,
    Gas: 222,
    Coal: 100,
    Renewables: 100,
    Wind: 70,
    Other: 200,
  },
];

export const currentEnergy = [
  {
    id: "Nuclear",
    label: "Nuclear",
    value: 100,
  },
  {
    id: "Bioenergy",
    label: "Bioenergy",
    value: 100,
  },
  {
    id: "Solar",
    label: "Solar",
    value: 293,
  },
  {
    id: "Hydro",
    label: "Hydro",
    value: 172,
  },
  {
    id: "Gas",
    label: "Gas",
    value: 222,
  },
  {
    id: "Coal",
    label: "Coal",
    value: 100,
  },
  {
    id: "Other Renewables",
    label: "Other Renewables",
    value: 100,
  },
  {
    id: "Wind",
    label: "Wind",
    value: 70,
  },
  {
    id: "Other Fossil Fuels",
    label: "Other Fossil Fuels",
    value: 200,
  },
];

export const phase_out_data = {
  no_coal: [
    "AL",
    "AT",
    "BE",
    "BY",
    "CD",
    "EG",
    "GE",
    "GH",
    "GN",
    "IR",
    "JM",
    "LV",
    "NE",
    "NG",
    "OM",
    "SD",
    "SE",
    "SV",
    "VE",
  ],
  ban_on_new_coal: ["ID", "DE"],
  phase_out_planned_by_2030: [
    "BE",
    "DK",
    "FI",
    "FR",
    "GR",
    "HU",
    "IE",
    "IT",
    "NL",
    "PT",
    "SK",
    "GB",
    "IL",
    "CA",
  ],
  phase_out_planned_by_2040: [
    "ZA",
    "CN",
    "IN",
    "ID",
    "JP",
    "KZ",
    "PK",
    "KR",
    "VN",
    "CR",
    "PA",
    "AN",
    "AT",
    "BE",
    "CZ",
    "DK",
    "FI",
    "FR",
    "DE",
    "GR",
    "HU",
    "IS",
    "IE",
    "IT",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "SE",
    "CH",
    "GB",
    "VA",
    "IL",
    "TR",
    "CA",
  ],
};

export const capacityChanges = {
  max: 1700,
  min: -700,
  OECD: [
    {
      Region: "OECD+EU 2021",
      Planned: 100,
      Construction: 40,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
    },
    {
      Region: "OECD+EU 2020",
      Planned: 100,
      Construction: 300,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
    },
    {
      Region: "OECD+EU 2019",
      Planned: 100,
      Construction: 100,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
    },
    {
      Region: "OECD+EU 2018",
      Planned: 100,
      Construction: 90,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
    },
    {
      Region: "OECD+EU 2017",
      Planned: 100,
      Construction: 100,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
    },
  ],
  CHINA: [
    {
      Region: "CHINA 2021",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
      Expected: -200,
    },
    {
      Region: "CHINA 2020",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
      Expected: -200,
    },
    {
      Region: "CHINA 2019",
      Planned: 100,
      Construction: 293,
      Retired: -323,
      Halted: 32,
      Cancelled: 111,
      Operational: 600,
      Expected: -200,
    },
    {
      Region: "CHINA 2018",
      Planned: 100,
      Construction: 293,
      Retired: -32,
      Halted: 424,
      Cancelled: 111,
      Operational: 600,
      Expected: -444,
    },
    {
      Region: "CHINA 2017",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
    },
  ],
  NONOECD: [
    {
      Region: "NON-OECD (NO CHINA) 2021",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
      Expected: -200,
    },
    {
      Region: "NON-OECD (NO CHINA) 2020",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
      Expected: -200,
    },
    {
      Region: "NON-OECD (NO CHINA) 2019",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
      Expected: -200,
    },
    {
      Region: "NON-OECD (NO CHINA) 2018",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
      Expected: -200,
    },
    {
      Region: "NON-OECD (NO CHINA) 2017",
      Planned: 100,
      Construction: 293,
      Retired: -172,
      Halted: 222,
      Cancelled: 100,
      Operational: 600,
      Expected: -200,
    },
  ],
};

export const electricityDemandData = [
  {
    id: "Indonesia",
    data: [
      { x: 2000, y: 10 },
      { x: 2001, y: 11 },
      { x: 2002, y: 12 },
      { x: 2003, y: 14 },
      { x: 2004, y: 12 },
      { x: 2005, y: 13 },
      { x: 2006, y: 11 },
      { x: 2007, y: 11 },
      { x: 2008, y: 13 },
      { x: 2009, y: 10 },
      { x: 2010, y: 9 },
      { x: 2011, y: 9 },
      { x: 2012, y: 9 },
      { x: 2013, y: 9 },
      { x: 2014, y: 9 },
      { x: 2015, y: 9 },
      { x: 2016, y: 9 },
      { x: 2017, y: 9 },
      { x: 2018, y: 9 },
      { x: 2019, y: 9 },
      { x: 2020, y: 8 },
    ],
  },
  {
    id: "World",
    data: [
      { x: 2000, y: 2 },
      { x: 2001, y: 5 },
      { x: 2002, y: 2 },
      { x: 2003, y: 3 },
      { x: 2004, y: 1 },
      { x: 2005, y: 1 },
      { x: 2006, y: 4 },
      { x: 2007, y: 4 },
      { x: 2008, y: 1 },
      { x: 2009, y: 1 },
      { x: 2010, y: 4 },
      { x: 2011, y: 2 },
      { x: 2012, y: 2 },
      { x: 2013, y: 3 },
      { x: 2014, y: 3 },
      { x: 2015, y: 1 },
      { x: 2016, y: 1 },
      { x: 2017, y: 4 },
      { x: 2018, y: 4 },
      { x: 2019, y: 2 },
      { x: 2020, y: 2 },
    ],
  },
];

export const electricityGenerationData = [
  {
    year: 2000,
    bioenergy: 1,
    coal: 163,
    gas: 15,
    hydro: 16,
    nuclear: 0,
    other_fossil: 2,
    other_renewables: 0,
    wind: 0,
    solar: 0,
  },
  {
    year: 2001,
    bioenergy: 1,
    coal: 168,
    gas: 23,
    hydro: 16,
    nuclear: 0,
    other_fossil: 2,
    other_renewables: 0,
    wind: 0,
    solar: 0,
  },
  {
    year: 2002,
    bioenergy: 2,
    coal: 165,
    gas: 29,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 0,
    solar: 0,
  },
  {
    year: 2003,
    bioenergy: 2,
    coal: 163,
    gas: 28,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 1,
    solar: 0,
  },
  {
    year: 2004,
    bioenergy: 2,
    coal: 174,
    gas: 27,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 1,
    solar: 0,
  },
  {
    year: 2005,
    bioenergy: 4,
    coal: 171,
    gas: 22,
    hydro: 15,
    nuclear: 0,
    other_fossil: 4,
    other_renewables: 0,
    wind: 1,
    solar: 0,
  },
  {
    year: 2006,
    bioenergy: 4,
    coal: 170,
    gas: 25,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 2,
    solar: 0,
  },
  {
    year: 2007,
    bioenergy: 4,
    coal: 174,
    gas: 31,
    hydro: 14,
    nuclear: 0,
    other_fossil: 4,
    other_renewables: 0,
    wind: 3,
    solar: 0,
  },
  {
    year: 2008,
    bioenergy: 5,
    coal: 171,
    gas: 34,
    hydro: 12,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 3,
    solar: 0,
  },
  {
    year: 2009,
    bioenergy: 3,
    coal: 171,
    gas: 39,
    hydro: 12,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 4,
    solar: 0,
  },
  {
    year: 2010,
    bioenergy: 3,
    coal: 167,
    gas: 44,
    hydro: 14,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 5,
    solar: 0,
  },
  {
    year: 2011,
    bioenergy: 2,
    coal: 163,
    gas: 46,
    hydro: 17,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 6,
    solar: 1,
  },
  {
    year: 2012,
    bioenergy: 3,
    coal: 158,
    gas: 48,
    hydro: 14,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 7,
    solar: 2,
  },
  {
    year: 2013,
    bioenergy: 3,
    coal: 148,
    gas: 50,
    hydro: 18,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 8,
    solar: 3,
  },
  {
    year: 2014,
    bioenergy: 4,
    coal: 143,
    gas: 50,
    hydro: 18,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 10,
    solar: 4,
  },
  {
    year: 2015,
    bioenergy: 4,
    coal: 151,
    gas: 48,
    hydro: 13,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 11,
    solar: 5,
  },
  {
    year: 2016,
    bioenergy: 4,
    coal: 154,
    gas: 46,
    hydro: 15,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 12,
    solar: 6,
  },
  {
    year: 2017,
    bioenergy: 4,
    coal: 148,
    gas: 51,
    hydro: 16,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 13,
    solar: 8,
  },
  {
    year: 2018,
    bioenergy: 4,
    coal: 149,
    gas: 49,
    hydro: 16,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 15,
    solar: 10,
  },
  {
    year: 2019,
    bioenergy: 4,
    coal: 142,
    gas: 52,
    hydro: 16,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 21,
    solar: 14,
  },
  {
    year: 2020,
    bioenergy: 3,
    coal: 135,
    gas: 48,
    hydro: 16,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 24,
    solar: 19,
  },
];

export const cumulative_generation_changes_sample = [
  {
    year: 2010,
    bioenergy: 1,
    coal: 1,
    gas: -13,
    hydro: 1,
    nuclear: 2,
    other_fossil: -6,
    other_renewables: 3,
    wind: -1,
    solar: 4,
    demand: 1.0,
  },
  {
    year: 2011,
    bioenergy: 2,
    coal: 1,
    gas: -10,
    hydro: -1,
    nuclear: -1,
    other_fossil: -4,
    other_renewables: 4,
    wind: -1,
    solar: 3,
    demand: 4.0,
  },
  {
    year: 2012,
    bioenergy: 1,
    coal: 1,
    gas: -2,
    hydro: -3,
    nuclear: -1,
    other_fossil: -4,
    other_renewables: 1,
    wind: 2,
    solar: 4,
    demand: 3.0,
  },
  {
    year: 2013,
    bioenergy: 1,
    coal: 3,
    gas: -4,
    hydro: 1,
    nuclear: -1,
    other_fossil: -2,
    other_renewables: 1,
    wind: 2,
    solar: 2,
    demand: 4.0,
  },
  {
    year: 2014,
    bioenergy: 1,
    coal: 1,
    gas: -2,
    hydro: 1,
    nuclear: -2,
    other_fossil: -3,
    other_renewables: 1,
    wind: 2,
    solar: 2,
    demand: 3.0,
  },
  {
    year: 2015,
    bioenergy: 2,
    coal: 2,
    gas: -1,
    hydro: 2,
    nuclear: -5,
    other_fossil: -1,
    other_renewables: 2,
    wind: 3,
    solar: 1,
    demand: 4.0,
  },
  {
    year: 2016,
    bioenergy: 2,
    coal: 1,
    gas: 6,
    hydro: -3,
    nuclear: 1,
    other_fossil: -2,
    other_renewables: 1,
    wind: 1,
    solar: 2,
    demand: 7.0,
  },
  {
    year: 2017,
    bioenergy: 2,
    coal: 1,
    gas: 13,
    hydro: -1,
    nuclear: -1,
    other_fossil: -11,
    other_renewables: 1,
    wind: 3,
    solar: 4,
    demand: 5.0,
  },
  {
    year: 2018,
    bioenergy: 2,
    coal: 4,
    gas: 17,
    hydro: 1,
    nuclear: -1,
    other_fossil: -16,
    other_renewables: 1,
    wind: 1,
    solar: 3,
    demand: 15.0,
  },
  {
    year: 2019,
    bioenergy: 1,
    coal: -1,
    gas: 15,
    hydro: -5,
    nuclear: 1,
    other_fossil: -21,
    other_renewables: 0,
    wind: 4,
    solar: 1,
    demand: 17.0,
  },
  {
    year: 2020,
    bioenergy: 1,
    coal: -1,
    gas: 16,
    hydro: -11,
    nuclear: 3,
    other_fossil: -21,
    other_renewables: 0,
    wind: 8,
    solar: 1,
    demand: 5.0,
  },
];

export const ElectricityMixOverTime = [
  {
    year: 2000,
    bioenergy: 1,
    coal: 163,
    gas: 15,
    hydro: 16,
    nuclear: 0,
    other_fossil: 2,
    other_renewables: 0,
    wind: 0,
    solar: 0,
  },
  {
    year: 2001,
    bioenergy: 1,
    coal: 168,
    gas: 23,
    hydro: 16,
    nuclear: 0,
    other_fossil: 2,
    other_renewables: 0,
    wind: 0,
    solar: 0,
  },
  {
    year: 2002,
    bioenergy: 2,
    coal: 165,
    gas: 29,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 0,
    solar: 0,
  },
  {
    year: 2003,
    bioenergy: 2,
    coal: 163,
    gas: 28,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 1,
    solar: 0,
  },
  {
    year: 2004,
    bioenergy: 2,
    coal: 174,
    gas: 27,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 1,
    solar: 0,
  },
  {
    year: 2005,
    bioenergy: 4,
    coal: 171,
    gas: 22,
    hydro: 15,
    nuclear: 0,
    other_fossil: 4,
    other_renewables: 0,
    wind: 1,
    solar: 0,
  },
  {
    year: 2006,
    bioenergy: 4,
    coal: 170,
    gas: 25,
    hydro: 16,
    nuclear: 0,
    other_fossil: 3,
    other_renewables: 0,
    wind: 2,
    solar: 0,
  },
  {
    year: 2007,
    bioenergy: 4,
    coal: 174,
    gas: 31,
    hydro: 14,
    nuclear: 0,
    other_fossil: 4,
    other_renewables: 0,
    wind: 3,
    solar: 0,
  },
  {
    year: 2008,
    bioenergy: 5,
    coal: 171,
    gas: 34,
    hydro: 12,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 3,
    solar: 0,
  },
  {
    year: 2009,
    bioenergy: 3,
    coal: 171,
    gas: 39,
    hydro: 12,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 4,
    solar: 0,
  },
  {
    year: 2010,
    bioenergy: 3,
    coal: 167,
    gas: 44,
    hydro: 14,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 5,
    solar: 0,
    demand: 0.0,
  },
  {
    year: 2011,
    bioenergy: 2,
    coal: 163,
    gas: 46,
    hydro: 17,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 6,
    solar: 1,
    demand: 4.0,
  },
  {
    year: 2012,
    bioenergy: 3,
    coal: 158,
    gas: 48,
    hydro: 14,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 7,
    solar: 2,
  },
  {
    year: 2013,
    bioenergy: 3,
    coal: 148,
    gas: 50,
    hydro: 18,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 8,
    solar: 3,
  },
  {
    year: 2014,
    bioenergy: 4,
    coal: 143,
    gas: 50,
    hydro: 18,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 10,
    solar: 4,
  },
  {
    year: 2015,
    bioenergy: 4,
    coal: 151,
    gas: 48,
    hydro: 13,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 11,
    solar: 5,
  },
  {
    year: 2016,
    bioenergy: 4,
    coal: 154,
    gas: 46,
    hydro: 15,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 12,
    solar: 6,
  },
  {
    year: 2017,
    bioenergy: 4,
    coal: 148,
    gas: 51,
    hydro: 16,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 13,
    solar: 8,
  },
  {
    year: 2018,
    bioenergy: 4,
    coal: 149,
    gas: 49,
    hydro: 16,
    nuclear: 0,
    other_fossil: 5,
    other_renewables: 0,
    wind: 15,
    solar: 10,
  },
  {
    year: 2019,
    bioenergy: 4,
    coal: 142,
    gas: 52,
    hydro: 16,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 21,
    solar: 14,
  },
  {
    year: 2020,
    bioenergy: 3,
    coal: 135,
    gas: 48,
    hydro: 16,
    nuclear: 0,
    other_fossil: 6,
    other_renewables: 0,
    wind: 24,
    solar: 19,
  },
];

export const cumulative_demand_changes = [
  {
    year: 2010,
    demand: 0.0,
  },
  {
    year: 2011,
    demand: 4.0,
  },
  {
    year: 2012,
    demand: 8.0,
  },
  {
    year: 2013,
    demand: 12.0,
  },
  {
    year: 2014,
    demand: 13.0,
  },
  {
    year: 2015,
    demand: 19.0,
  },
  {
    year: 2016,
    demand: 21.0,
  },
  {
    year: 2017,
    demand: 21.0,
  },
  {
    year: 2018,
    demand: 21.0,
  },
  {
    year: 2019,
    demand: 17.0,
  },
  {
    year: 2020,
    demand: 15.0,
  },
];

export const newsFeedArticleData = [
  {
    title:
      "China, Japan and South Korea must work together to end coal use and funding",
    content:
      "To meet the goals of the Paris Agreement we need to end the construction of all new coal plants, close a coal plant a day between now and 2040 and accelerate the expansion of renewable power, writes former United Nations secretary general Ban Ki-Moon in the South China Morning Post.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "18 MARCH 2021",
  },
  {
    title:
      "Energy financiers in Asia must stop supporting region’s costly addiction to LNG and coal power",
    content:
      "Multilateral development banks’ support for coal and LNG plants in Asia will lead to unsustainable fossil fuel subsidies, rising power tariffs and undermine development, writes Simon Nicholas from the Institute for Energy Economics and Financial Analysis in the South China Morning Post.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "05 MARCH 2021",
  },
  {
    title: "How can NSW allow new coalmines while committing to net-zero emissions?",
    content:
      "The New South Wales Government is simultaneously committed to a net-zero emissions target for 2050 and supporting the development of a raft of new coal mines in the Hunter Valley, writes Richard Denniss from The Australia Institute in The Guardian.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "01 SEPTEMBER 2020",
  },
  {
    title: "Japanese utility rules out new coal plant",
    content:
      "Japanese NGOs have welcomed the decision of plans of Electric Power Development Company (J-Power) and Ube Industries to cancel the proposed 600 MW Nishiokinoyama Power Plant in western Japan ",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "18 MARCH 2021",
  },
  {
    title: "NSW Government buys out Shenhua lease to end mining plan",
    content:
      "The New South Wales Government has paid A$100 million (US$77 million) to buy out Shenhua’s proposed Watermark coal mine in the Hunter Valley ",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "05 MARCH 2021",
  },
  {
    title: "Study finds cost of finance for coal project soaring",
    content:
      "A study by the Oxford Sustainable Finance Programme has found investors in coal companies and projects now require returns of 40 per cent to offset stranded asset and other risks ",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "01 SEPTEMBER 2020",
  },
];

export const regionalNewsData = [
  {
    title: "Report argues Indonesia\u2019s 2060 pledge lacks crucial details: ",
    summary:
      "A report by the Institute for Energy Economics and Financial Analysis (IEEFA) argues that Indonesia\u2019s Ministry of Energy and Mineral Resources current energy policies are inconsistent with President Jokowi\u2019s pledge to achieve carbon neutrality by 2060. IEEFA said no early coal plant retirements have been proposed and 16,000 MW of new coal plants are still proceeding despite overcapacity in the main Java-Bali and Sumatra grid. While the 2021 draft Power Sector Business Plan reduces forecast demand growth from 6.4 per cent a year to 4.9 per cent a year, it continues to sideline solar and wind capacity in favour of biomass co-firing at coal plants plus new large hydro and geothermal projects. IEEFA notes the draft power plan appears to shelve 6800 MW of proposed coal plants \u2013 nearly all proposed by the publicly owned utility PLN or its subsidiaries \u2013 and substitute \u201crenewable baseload\u201d plants for them. (Institute for Energy Economics and Financial Analysis)",
    links: [
      "https://ieefa.org/ieefa-indonesias-state-owned-utility-plns-2060-net-zero-ambition-not-without-flaws-and-gaps/",
    ],
    date: "01 SEPTEMBER 2020",
  },
  {
    title:
      "Vietnam police arrest founder of group that cosigned Greenpeace letter: ",
    summary:
      "Hanoi Police have arrested Dang Dinh Bach, the founder of a Vietnamese NGO group, and ordered he be detained for three months while possible \u201ctax evasion\u201d charges are investigated. In late May Bach\u2019s group, The Law and Policy of Sustainable Development Research Center, was one of 10 co-signatories on a Greenpeace letter to South Korea\u2019s President Moon Jae-in. The letter urged President Moon to adopt a far more ambitious position on the financing of international coal projects ahead of the P4G summit later that month. Police also arrested Mai Phan Lo, the president of the Center for Media in Educating the Community on identical charges of \u201ctax evasion\u201d on the same day. Human Rights Watch, a US NGO, estimates over 130 political human rights activists, environmentalists and others have been imprisoned for exercising their basic rights. (Nguoi Lao Dong [Vietnamese], Nguoi Lao Dong [Vietnamese])",
    links: [
      "https://nld.com.vn/phap-luat/mot-giam-doc-trung-tam-nghien-cuu-bi-bat-ve-toi-tron-thue-20210703080644702.htm",
      "https://nld.com.vn/phap-luat/ong-mai-phan-loi-bi-bat-ve-toi-tron-thue-20210702191758134.htm",
    ],
    date: "01 SEPTEMBER 2020",
  },
  {
    title: "Cambodia embraces dirty energy fearing drought-driven shortages",
    summary:
      "As climate change and drought has crimped the country\u2019s hydro generation, the Cambodian Government has turned to new fossil fuel projects including a coal plant in the Botum Sakor National Park, write Danielle Keeton-Olsen and Yon Sineat in The Third Pole.",
    links: [
      "https://www.thethirdpole.net/en/energy/cambodia-embraces-dirty-energy-fearing-drought-driven-shortages/",
    ],
    date: "01 SEPTEMBER 2020",
  },
];

export const globalNewsData = [
  {
    title: "In Goa, the water runs black",
    summary:
      "Locals near one of India\u2019s coal-importing ports feel the effects of coal dust and are bracing for an even unhealthier future, writes Disha Shetty in Hakai Magazine.",
    links: ["https://www.hakaimagazine.com/features/in-goa-the-water-runs-black/"],
    date: "01 SEPTEMBER 2020",
  },
  {
    title:
      "Who saved Alberta\u2019s mountaintops and precious, clean water? Albertans",
    summary:
      "The Grassy Mountain coal mine project is dead, but only because of a grassroots rebellion by the people of Alberta, writes Andrew Nikiforuk in The Tyee.",
    links: [
      "https://thetyee.ca/Analysis/2021/06/18/Alberta-Mountaintops-Precious-Clean-Water-Saved-Albertans/",
    ],
    date: "01 SEPTEMBER 2020",
  },
  {
    title: "Report argues Indonesia\u2019s 2060 pledge lacks crucial details: ",
    summary:
      "A report by the Institute for Energy Economics and Financial Analysis (IEEFA) argues that Indonesia\u2019s Ministry of Energy and Mineral Resources current energy policies are inconsistent with President Jokowi\u2019s pledge to achieve carbon neutrality by 2060. IEEFA said no early coal plant retirements have been proposed and 16,000 MW of new coal plants are still proceeding despite overcapacity in the main Java-Bali and Sumatra grid. While the 2021 draft Power Sector Business Plan reduces forecast demand growth from 6.4 per cent a year to 4.9 per cent a year, it continues to sideline solar and wind capacity in favour of biomass co-firing at coal plants plus new large hydro and geothermal projects. IEEFA notes the draft power plan appears to shelve 6800 MW of proposed coal plants \u2013 nearly all proposed by the publicly owned utility PLN or its subsidiaries \u2013 and substitute \u201crenewable baseload\u201d plants for them. (Institute for Energy Economics and Financial Analysis)",
    links: [
      "https://ieefa.org/ieefa-indonesias-state-owned-utility-plns-2060-net-zero-ambition-not-without-flaws-and-gaps/",
    ],
    date: "01 SEPTEMBER 2020",
  },
];

export const analysisData = [
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Colombian regulator rejects Glencore bid to surrender Prodeco licences",
    content:
      "Colombia\u2019s mining regulator, ANM, has rejected Prodeco\u2019s request to relinquish three mining titles for mines it suspended production in March 2019 due to the downturn in coal demand caused by the COVID-19 pandemic. Prodeco, a subsidiary of Glencore, produced 13 million tonnes of coal from the three mines in 2019. The company wants to relinquish the mining titles to eliminate the care and maintenance costs of the mines even though the price for Colombia coal has increased by over 130 per cent in the last year. Prodeco has appealed against ANM\u2019s decision and is expecting a final decision on July 20. Glencore is the world\u2019s largest exporter of thermal coal with mines in Australia and South Africa. (Argus)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1523848309072-c199db53f137?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "The rise and fall of coal: 2020 transition trends",
    content:
      "The Covid-19 pandemic heavily impacted coal power generation during 2020, particularly during H1. Steep declines in demand for electricity resulted in even larger falls in coal generation.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1541427468627-a89a96e5ca1d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "The rise and fall of coal: 2020 transition trends",
    content:
      "The Covid-19 pandemic heavily impacted coal power generation during 2020, particularly during H1. Steep declines in demand for electricity resulted in even larger falls in coal generation.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "The rise and fall of coal: 2020 transition trends",
    content:
      "The Covid-19 pandemic heavily impacted coal power generation during 2020, particularly during H1. Steep declines in demand for electricity resulted in even larger falls in coal generation.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1523848309072-c199db53f137?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "The rise and fall of coal: 2020 transition trends",
    content:
      "The Covid-19 pandemic heavily impacted coal power generation during 2020, particularly during H1. Steep declines in demand for electricity resulted in even larger falls in coal generation.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1541427468627-a89a96e5ca1d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "The rise and fall of coal: 2020 transition trends",
    content:
      "The Covid-19 pandemic heavily impacted coal power generation during 2020, particularly during H1. Steep declines in demand for electricity resulted in even larger falls in coal generation.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "The rise and fall of coal: 2020 transition trends",
    content:
      "The Covid-19 pandemic heavily impacted coal power generation during 2020, particularly during H1. Steep declines in demand for electricity resulted in even larger falls in coal generation.",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1523848309072-c199db53f137?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
  {
    title: "Philippines utility scraps three coal plants",
    content:
      "San Miguel Corporation (SMC) has informed the Philippines Department of Energy (DOE) it has dropped plans for three coal plants which have a combined capacity of 1500 MW. In a July 1 letter to the Center for Energy, Ecology and Development the DOE stated SMC has \u201cdiscontinued\u201d plans for the 600 MW Ibabang plant, the 600 MW Sariaya plant and the 300 MW Looc Malabuyoc plant. The letter also confirmed three other projects \u2013 the 300 MW expansion of SMC\u2019s Malita plant, the proposed 600 MW Merbau plant and the 300 MW Ozamiz plants \u2013 had all been removed from the DOE\u2019s list of potential projects \u201cdue to non-submission of the required monthly power project updates.\u201d DOE also confirmed Meralco was in discussions with lenders as it had had encountered \u201cchallenges\u201d in securing power purchase agreements for its proposed 1336 MW Atimonan plant. Monsignor Noel Villareal, a Catholic Church leader who has campaigned against the coal plants, welcomed DOE\u2019s confirmation of the end of the three projects and said he hoped other projects such as the Atimonan plant would also be cancelled. (Business World)",
    link: "https://www.e3g.org/our-work/fossil-fuel-transition/#coal",
    date: "August 05, 2021",
    image:
      "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=350&q=80",
  },
];
